language: c

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -q install valgrind

script:
  - ./autogen.sh
  - ./configure && make distcheck VERBOSE=1 && make clean
  - ./configure --enable-valgrind-tests && make distcheck VERBOSE=1
    DISTCHECK_CONFIGURE_FLAGS="--enable-valgrind-tests"
