language: c

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get -q install valgrind lcov
  - sudo pip install cpp-coveralls

script:
  - ./autogen.sh
  - ./configure && make distcheck VERBOSE=1 && make clean
  - ./configure --enable-valgrind-tests && make distcheck VERBOSE=1 DISTCHECK_CONFIGURE_FLAGS="--enable-valgrind-tests" && make clean
  - if [ "$CC" = "gcc" ]; then ./configure --enable-code-coverage && make && make check; fi
after_success:
  - if [ "$CC" = "gcc" ]; then cpp-coveralls --build-root . --exclude t/ --exclude /usr/include; fi
